spring:
  application:
    name: BookingTransportService

  data:
    mongodb:
      uri: mongodb+srv://sachini:transport0828@cluster0.ut2bgsg.mongodb.net/transportdb?retryWrites=true&w=majority

server:
  port: 8088